### ISSUE TITLE
Missing semver dependency

### ISSUE THREAD

**Issue by kub1x** [boneskull/node-environment-flags#2]
The `semver` package is used, yet it is missing in `dependencies` field in `package.json`. This is an issue as it is probably a leaked dependency from `mocha` and causes it to fail to run when installed using `pnpm`.

**Comment by kub1x** [comment]
Adding for reference the `pnpmfile.js` snippet to workaround this issue. 
```javascript
module.exports = { hooks: { readPackage } }

function readPackage (pkg) {
  switch (pkg.name) {
    case 'node-environment-flags':
      pkg.dependencies.semver = '*';
      break;
  }
  return pkg;
}
```

**Comment by SoyYoRafa** [comment]
Agreed. I sent a pull request.
